ALTER TABLE endpoints ADD COLUMN api_candidate INTEGER NOT NULL DEFAULT 0;
ALTER TABLE endpoints ADD COLUMN api_evidence TEXT NOT NULL DEFAULT '';
ALTER TABLE endpoints ADD COLUMN response_content_type TEXT NOT NULL DEFAULT '';
ALTER TABLE parameters ADD COLUMN provenance TEXT NOT NULL DEFAULT 'REQUEST_INPUT';
