package cmdinjection

// labCommand is a deliberately FAKE command name -- never "echo", never
// any real shell builtin or binary -- recognized only by the Phase 3.7
// Test Lab's own simulated grammar
// (lab/harness_vuln.go's cmdInjectionPattern). Nothing in this
// package, or anywhere else in sakanner, ever invokes a real shell;
// this string exists purely as a safe, deterministic, lab-only
// protocol both sides agree on. See
// docs/phase-3-7-command-injection.md "Test lab architecture."
const labCommand = "sakanner_lab_echo"

// markerPrefix plus an exact, freshly generated per-probe token is the
// ONLY thing this detector ever treats as execution proof (section 5's
// "strong proof requires: controlled execution marker generated by the
// lab fixture," section 11's per-probe correlation requirement).
const markerPrefix = "COMMAND_INJECTION_MARKER:"

// commandVariant is one wire representation of an injection attempt --
// a template with "%s" where the correlation token belongs, sent
// EXACTLY as shown (never re-escaped further -- see requestURL).
type commandVariant struct {
	name     string // short, human-readable label for evidence/logs
	template string // %s replaced with the fresh per-probe token
}

// commandVariants returns a small, fixed, deterministic set --
// explicitly NOT a large payload dictionary (section 13's "do not
// create dozens of payloads," matching exactly the 3 the task
// requires: basic, a separator variant, and an encoded variant).
//
// Every variant percent-encodes the space between the lab command name
// and its token as "%20" -- a literal, unescaped space is not valid
// inside an HTTP request line at all (Go's own http.Client silently
// fails to deliver a request built with one), so no representation
// here could ever send one raw regardless of injection intent; this
// mirrors how a real attacker's browser or HTTP client would also
// never transmit a literal space.
//
// The three separators are deliberately NOT treated uniformly: "|" is
// sent completely raw (Go's net/url query decoding leaves it alone),
// while ";" and "&&" are percent-encoded. This is not a stylistic
// choice -- Go's own url.ParseQuery treats a raw, unescaped ";" as an
// ALTERNATE parameter delimiter (a long-standing historical quirk of
// the net/url package, still present in this Go version), silently
// splitting "host=" (empty) from a second, keyless parameter rather
// than preserving ";..." as part of "host"'s value; "&" is the
// standard delimiter and would be split identically if sent raw. Only
// percent-encoding survives standard query-string transport for these
// two separators -- confirmed directly against a real net/http server,
// not assumed (see docs/phase-3-7-command-injection.md "Controlled
// probes" for the concrete before/after proof).
func commandVariants() []commandVariant {
	return []commandVariant{
		{name: "pipe (raw)", template: "|" + labCommand + "%%20%s"},
		{name: "semicolon (percent-encoded)", template: "%%3B" + labCommand + "%%20%s"},
		{name: "double-ampersand (percent-encoded)", template: "%%26%%26" + labCommand + "%%20%s"},
	}
}
